"""
Django settings for nglog_backend project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

# TODO: divide up settings file

# TODO: user name and password
import os
import secret
from mongoengine import connect

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = secret.SECRET_KEY
MDB_NAME = secret.MDB_NAME
MDB_USER = secret.MDB_USER
MDB_PASS = secret.MDB_PASS
ADB_NAME = secret.ADB_NAME
ADB_USER = secret.MDB_USER
ADB_PASS = secret.MDB_PASS

# TODO: change for prod
DEBUG = True
ALLOWED_HOSTS = []


# base django apps
DJANGO_BASE_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
# add third party apps here
PREREQ_APPS = [

]
# add nglog backend apps here
PROJECT_APPS = [
    'engine',
    'users',
]
INSTALLED_APPS = DJANGO_BASE_APPS + PREREQ_APPS + PROJECT_APPS


# add base middleware here
BASE_MIDDLEWARE = [
    # base
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
]
# add third party middleware here
PROJECT_MIDDLEWARE = [

]
MIDDLEWARE = BASE_MIDDLEWARE + PROJECT_MIDDLEWARE


ROOT_URLCONF = 'nglog_backend.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'nglog_backend.wsgi.application'


# TODO: set up session database
# MongoDB connection
connect(secret.MDB_NAME, username=secret.MDB_USER, password=secret.MDB_PASS)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy'
    },
}


# AUTHENTICATION_BACKENDS = ('mongoengine.django.auth.MongoEngineBackend',)
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# TODO: make dynamic
# https://docs.djangoproject.com/en/1.10/topics/i18n
TIME_ZONE = 'America/Vancouver'

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
